#install.packages('ggplot2', repos = "http://cran.us.r-project.org")
#install.packages('RZooRoH', repos = "http://cran.us.r-project.org")
library(ggplot2)
library(RZooRoH)
mix2_10 <- zoomodel(K=10,base=2)
FJS_file <- "FJS.gen.trans"
FJS_samples <- "FJS.txt"
FJS_GT <- zoodata(FJS_file,zformat="gp", samplefile = FJS_samples)
FJS_2_10_results <- zoorun(mix2_10, FJS_GT,nT=40, localhbd = TRUE)
allseg_FJS<-rohbd(zres=FJS_2_10_results)
write.table(allseg_FJS$length,file="FJS_2_10.g.rohseg")
write.table(allseg_FJS,file="FJS_2_10.rohbd",col.names = TRUE)
write.table(FJS_2_10_results@realized,file="FJS_2_10.realized")
sink("FJSROH.txt")           
cat(summary(allseg_FJS$length),file="FJSROH.txt",sep="\t",append=TRUE)
sink()
pdf("FJS_2_10.hist.pdf")
hist(allseg_FJS$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("FJS_2_10.boxplot.pdf")
zooplot_prophbd(list(FJS=FJS_2_10_results),style='boxplot',cols="#285178")
dev.off()
pdf("FJS_2_10.indiv_lines.pdf")
zooplot_individuals(list(FJS=FJS_2_10_results),cumulative=TRUE)
dev.off()
pdf("FJS_2_10.partition.pdf")
zooplot_partitioning(list(FJS=FJS_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
##########
HS_file <- "HS.gen.trans"
HS_samples <- "HS.txt"
HS_GT <- zoodata(HS_file,zformat="gp", samplefile = HS_samples)
HS_2_10_results <- zoorun(mix2_10, HS_GT,nT=40, localhbd = TRUE)
allseg_HS<-rohbd(zres=HS_2_10_results)
write.table(allseg_HS$length,file="HS_2_10.g.rohseg")
write.table(allseg_HS,file="HS_2_10.rohbd",col.names = TRUE)
write.table(HS_2_10_results@realized,file="HS_2_10.realized")
sink("HSROH.txt")           
cat(summary(allseg_HS$length),file="HSROH.txt",sep="\t",append=TRUE)
sink()
pdf("HS_2_10.hist.pdf")
hist(allseg_HS$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("HS_2_10.boxplot.pdf")
zooplot_prophbd(list(U=HS_2_10_results),style='boxplot',cols="#C55000")
dev.off()
pdf("HS_2_10.indiv_lines.pdf")
zooplot_individuals(list(HS=HS_2_10_results),cumulative=TRUE)
dev.off()
pdf("HS_2_10.partition.pdf")
zooplot_partitioning(list(U=HS_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
################
MS_file <- "MS.gen.trans"
MS_samples <- "MS.txt"
MS_GT <- zoodata(MS_file,zformat="gp", samplefile = MS_samples)
MS_2_10_results <- zoorun(mix2_10, MS_GT,nT=40, localhbd = TRUE)
allseg_MS<-rohbd(zres=MS_2_10_results)
write.table(allseg_MS$length,file="MS_2_10.g.rohseg")
write.table(allseg_MS,file="MS_2_10.rohbd",col.names = TRUE)
write.table(MS_2_10_results@realized,file="MS_2_10.realized")
sink("MSROH.txt")           
cat(summary(allseg_MS$length),file="MS_ROH.txt",sep="\t",append=TRUE)
sink()
pdf("MS_2_10.hist.pdf")
hist(allseg_MS$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("MS_2_10.boxplot.pdf")
zooplot_prophbd(list(MS=MS_2_10_results),style='boxplot',cols="#DCCF3D")
dev.off()
pdf("MS_2_10.indiv_lines.pdf")
zooplot_individuals(list(MS=MS_2_10_results),cumulative=TRUE)
dev.off()
pdf("MS_2_10.partition.pdf")
zooplot_partitioning(list(MS=MS_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
###########
SC_file <- "SC.gen.trans"
SC_samples <- "SC.txt"
SC_GT <- zoodata(SC_file,zformat="gp", samplefile = SC_samples)
SC_2_10_results <- zoorun(mix2_10, SC_GT,nT=40, localhbd = TRUE)
allseg_SC<-rohbd(zres=SC_2_10_results)
write.table(allseg_SC$length,file="SC_2_10.g.rohseg")
write.table(allseg_SC,file="SC_2_10.rohbd",col.names = TRUE)
write.table(SC_2_10_results@realized,file="SC_2_10.realized")
sink("SCROH.txt")           
cat(summary(allseg_SC$length),file="SCROH.txt",sep="\t",append=TRUE)
sink()
pdf("SC_2_10.hist.pdf")
hist(allseg_SC$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("SC_2_10.boxplot.pdf")
zooplot_prophbd(list(SC=SC_2_10_results),style='boxplot',cols="#2485BC")
dev.off()
pdf("SC_2_10.indiv_lines.pdf")
zooplot_individuals(list(SC=SC_2_10_results),cumulative=TRUE)
dev.off()
pdf("SC_2_10.partition.pdf")
zooplot_partitioning(list(SC=SC_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
#########
WYL_file <- "WYL.gen.trans"
WYL_samples <- "WYL.txt"
WYL_GT <- zoodata(WYL_file,zformat="gp", samplefile = WYL_samples)
WYL_2_10_results <- zoorun(mix2_10, WYL_GT,nT=40, localhbd = TRUE)
allseg_WYL<-rohbd(zres=WYL_2_10_results)
write.table(allseg_WYL$length,file="WYL_2_10.g.rohseg")
write.table(allseg_WYL,file="WYL_2_10.rohbd",col.names = TRUE)
write.table(WYL_2_10_results@realized,file="WYL_2_10.realized")
sink("WYLROH.txt")           
cat(summary(allseg_WYL$length),file="WYLROH.txt",sep="\t",append=TRUE)
sink()
pdf("WYL_2_10.hist.pdf")
hist(allseg_WYL$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("WYL_2_10.boxplot.pdf")
zooplot_prophbd(list(WYL=WYL_2_10_results),style='boxplot',cols="#D79506")
dev.off()
pdf("WYL_2_10.indiv_lines.pdf")
zooplot_individuals(list(WYL=WYL_2_10_results),cumulative=TRUE)
dev.off()
pdf("WYL_2_10.partition.pdf")
zooplot_partitioning(list(WYL=WYL_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
#################
YG_file <- "YG.gen.trans"
YG_samples <- "YG.txt"
YG_GT <- zoodata(YG_file,zformat="gp", samplefile = YG_samples)
YG_2_10_results <- zoorun(mix2_10, YG_GT,nT=40, localhbd = TRUE)
allseg_C<-rohbd(zres=YG_2_10_results)
write.table(allseg_YG$length,file="YG_2_10.g.rohseg")
write.table(allseg_YG,file="YG_2_10.rohbd",col.names = TRUE)
write.table(YG_2_10_results@realized,file="YG_2_10.realized")
sink("YGROH.txt")           
cat(summary(allseg_YG$length),file="YGROH.txt",sep="\t",append=TRUE)
sink()
pdf("YG_2_10.hist.pdf")
hist(allseg_YG$length/1000000,xlab="Length of HBD segment (in cM)",main="",col='tomato',nc=100)
dev.off()
pdf("YG_2_10.boxplot.pdf")
zooplot_prophbd(list(YG=YG_2_10_results),style='boxplot',cols="#50B2E9")
dev.off()
pdf("YG_2_10.indiv_lines.pdf")
zooplot_individuals(list(YG=YG_2_10_results),cumulative=TRUE)
dev.off()
pdf("YG_2_10.partition.pdf")
zooplot_partitioning(list(YG=YG_2_10_results), ylim = c(0,0.5), nonhbd = FALSE)
dev.off()
############################画比例
dtFJS <- zoodoris(zres = FJS_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
dtHS <- zoodoris(zres = HS_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
dtMS <- zoodoris(zres = MS_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
dtSC <- zoodoris(zres = SC_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
dtWYL <- zoodoris(zres = WYL_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
dtYG <- zoodoris(zres = YG_2_10_results, minv = 1, maxv = 25, glen = 2450, method = "sharing")
)
pdf("all.HBD_segment_proportion.pdf")
matplot(dtFJS$win_st,cbind(dtFJS$sharing,dtHS$sharing,dtMS$sharing,dtSC$sharing,dtWYL$sharing,dtYG$sharing),
	        xlab = 'Length of HBD segment in cM', ylab = 'Proportion of the genome',
		        type ='l', pch=c(21,21,21),bg=c('#285178','#C55000','#DCCF3D','#2485BC','#D79506','#50B2E9'),
		        col=c('#285178','#C55000','#DCCF3D','#2485BC','#D79506','#50B2E9'))
dev.off()
#####################
pdf("all.HBD2_10.pdf")
zooplot_prophbd(list(FJS=FJS_2_10_results,HS=HS_2_10_results,MS=MS_2_10_results,SC=SC_2_10_results,WYL=WYL_2_10_results,YG=YG_2_10_results),style='barplot')
dev.off()
pdf("all.averageIC2_10.pdf")
zooplot_prophbd(list(FJS=FJS_2_10_results,HS=HS_2_10_results,MS=MS_2_10_results,SC=SC_2_10_results,WYL=WYL_2_10_results,YG=YG_2_10_results),style='lines', cumulative = TRUE)
dev.off()
pdf("all.averageIC2_10.no-cumulative.pdf")
zooplot_prophbd(list(FJS=FJS_2_10_results,HS=HS_2_10_results,MS=MS_2_10_results,SC=SC_2_10_results,WYL=WYL_2_10_results,YG=YG_2_10_results),style='lines', cumulative = FALSE)
dev.off()
pdf("all.partition2_10.pdf")
zooplot_partitioning(list(FJS=FJS_2_10_results,HS=HS_2_10_results,MS=MS_2_10_results,SC=SC_2_10_results,WYL=WYL_2_10_results,YG=YG_2_10_results), plotids = FALSE,ylim=c(0,0.5), nonhbd = FALSE)
dev.off()
